# -------------------------------------------------------------------------
# Set the active profiles.
# -------------------------------------------------------------------------
spring:
  profiles:
    active: production

server:
  port: 8080

# -------------------------------------------------------------------------
# Microservice Service Registration
# -------------------------------------------------------------------------
microservice:
  basePath: services
  server:
    name: topics/publisher/v1

activemq:
  username: admin
  password: admin
  broker:
    connectionString: tcp://localhost:61616
